"""
CV Generator — /cv command

Formats the user's Skills Passport into a clean, employer-readable CV.
No external API needed — pure formatting from passport data.
"""

import logging
from datetime import datetime

import httpx
from telegram import Update
from telegram.ext import ContextTypes

logger = logging.getLogger(__name__)
import os
API_BASE = os.environ.get("API_BASE_URL", "http://localhost:8000")


def _bar(pct: float, width: int = 10) -> str:
    filled = round(pct / 100 * width)
    return "█" * filled + "░" * (width - filled)


def _evidence_badge(evidence_type: str) -> str:
    return {
        "employer_verified": "[Employer-verified]",
        "assessed":          "[Assessed]        ",
        "peer_vouched":      "[Peer-vouched]    ",
        "self_report":       "[Self-reported]   ",
    }.get(evidence_type, "[Self-reported]   ")


def _tier_star(evidence_type: str) -> str:
    return {
        "employer_verified": "★",
        "assessed":          "◆",
        "peer_vouched":      "●",
        "self_report":       "○",
    }.get(evidence_type, "○")


async def cv_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    telegram_id = str(update.effective_user.id)
    name = update.effective_user.first_name or "Worker"

    await update.message.reply_text("Generating your Skills CV…")

    async with httpx.AsyncClient(timeout=10.0) as client:
        try:
            passport_resp = await client.get(f"{API_BASE}/skills/passport/by_user/{telegram_id}")
            passport = passport_resp.json() if passport_resp.status_code == 200 else None
        except Exception:
            passport = None

    if not passport:
        await update.message.reply_text(
            "No passport found. Complete /interview first to generate your CV."
        )
        return

    skills = passport.get("skills", [])
    country = passport.get("country_iso", "GHA")
    issued = (passport.get("issued_at") or "")[:10]
    passport_id = (passport.get("passport_id") or "")[:8]

    regular = [s for s in skills if not s.get("is_heritage_skill")]
    heritage = [s for s in skills if s.get("is_heritage_skill")]

    peer_plus = sum(1 for s in skills if s.get("evidence_type") in ("peer_vouched", "employer_verified", "assessed"))
    strength = min(100, len(skills) * 10 + peer_plus * 5)

    lines = [
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
        f"  SKILLS CV  —  {name.upper()}",
        "  Generated by UNMAPPED Protocol",
        f"  {datetime.utcnow().strftime('%B %Y')} | {country}",
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
        "",
        "PASSPORT STRENGTH",
        f"  {_bar(strength)} {strength}/100",
        "",
    ]

    if regular:
        lines.append("VERIFIED SKILLS")
        for s in regular[:8]:
            star  = _tier_star(s.get("evidence_type", "self_report"))
            badge = _evidence_badge(s.get("evidence_type", "self_report"))
            conf  = round(s.get("confidence", 0.7) * 100)
            label = s.get("skill_label", "Unknown skill")[:32]
            lines.append(f"  {star} {label:<32} {badge} {_bar(conf, 8)} {conf}%")
        lines.append("")

    if heritage:
        lines.append("HERITAGE SKILLS")
        lines.append("  (LMIC-specific competencies invisible to formal CVs)")
        for s in heritage[:5]:
            lines.append(f"  ✦ {s.get('skill_label', '')}")
        lines.append("")

    lines += [
        "AUTOMATION RESILIENCE",
        f"  Calibrated risk for {country}: see /readiness",
        "  Source: Frey & Osborne (2013) + LMIC adjustment",
        "",
        "VERIFICATION",
        f"  Passport ID: {passport_id}…",
        f"  Issued: {issued}",
        "  Standard: UNMAPPED Open Protocol v1.0",
        "  Verify at: /webapp/passport.html",
        "",
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
        "  Share this with any employer.",
        "  Every skill here is cited.",
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    ]

    await update.message.reply_text(
        "```\n" + "\n".join(lines) + "\n```",
        parse_mode="Markdown",
    )
